### ISSUE TITLE
Touch Bar is not locked

### ISSUE THREAD

**Issue by displacement** [kfv/keylock#1]
I am running a MacBookPro17,1 with Sonoma 14.1.1 and the Touch Bar does not lock when the app is invoked.

**Comment by kfv** [comment]
Hey, thanks for pointing out the Touch Bar issue–I admit it had slipped my mind. I'll dive into this and aim to resolve it as soon as possible. Fortunately, I have an MBP with Touch Bar available for testing, so I'll get on it shortly. Cheers!

**Comment by kfv** [comment]
Hey, sorry if it took me a bit long to come back to this issue. I just tested keylock on an MBP with Touch Bar, and it works exactly the same way it treats FN keys on a regular device with no touch bar available. The only note here is some special keys I cannot lock, as described in the [Usage](https://github.com/kfv/keylock#usage) section of the project's README:

> Not every key is locked, though; Brightness, Play/Pause, Rewind, Fast Forward, Volume, and Caps Lock keys are not locked. Mouse movement is also intact.

But to improve the UX, maybe I could just display a lock message or something on the touch bar once the app's running... haven't checked the API, yet, but might do shortly.

I'm going to close the issue, but feel free to reopen it for any sort of recommendation or requests related to the concern.

Thank you so much again. Cheers.
